### ISSUE TITLE
Key problem in SlidesLive.py

### ISSUE THREAD

**Issue by arash1902** [So-Cool/myslideslive#1]
I tried the given example but it throws the following error:
```
File "slideslive.py", line 494, in __init__
    self.video_description['slides_xml_url'], approach='xml')
KeyError: 'slides_xml_url'
```

Any help is appreciated.

**Comment by So-Cool** [comment]
I would need some more details. Can you describe the setting in which this happens? E.g., OS, Python and package versions, and, most important, the exact command you execute to get the error.

**Comment by arash1902** [comment]
I used the following command:

**Comment by arash1902** [comment]
I used the following commad:
```
msl = SlidesLive('https://slideslive.com/38956531/'
                 'beyond-static-papers-'
                 'rethinking-how-we-share-scientific-understanding-in-ml')
```

I used Pycharm 2020.1.2, python 3.6.3, and Windows 10.

**Comment by arash1902** [comment]
I also tried it on Ubuntu 18.04, and python 3.6 and used the terminal command:
```
msl --slide 1074 1075 \
https://slideslive.com/38956531/beyond-static-papers-rethinking-how-we-share-scientific-understanding-in-ml
```
and it throws the same error.

**Comment by So-Cool** [comment]
The `0.2` release (now available on [pip](https://pypi.org/project/myslideslive/#history)) should fix the issue. Let me know if you come across any other problems.

**Comment by arash1902** [comment]
Thank you. It works perfectly.
