### ISSUE TITLE
UnboundLocalError in ffmpeg_concat_script

### ISSUE THREAD

**Issue by retkowski** [So-Cool/myslideslive#6]
The following line results in a UnboundLocalError since the local variable `i` is referred to before it is assigned:

https://github.com/So-Cool/myslideslive/blob/6960ffbf986bdeb3756fa49a49480a0824e8a412/myslideslive/slideslive.py#LL462C52-L462C56

**Comment by So-Cool** [comment]
Could you please provide code to reproduce this error?

**Comment by retkowski** [comment]
To reproduce this error, you need a video that only has one slide:

```python
url = "https://slideslive.com/38967490"
msl = SlidesLive(url)
msl.download_slides(directory=Path("slides"))
msl.compose_video()
```

**Comment by So-Cool** [comment]
Release 0.4 (available on master and pypi) should fix this.
